---
nix:
  enable: true
templates:
  params:
    author-email: terlar@gmail.com
    copyright: ! 'Copyright: (c) 2016 Terje Larsen'
    category: Library
    github-username: terlar
    author-name: Terje Larsen
