export TERM="xterm-256color"

# Locale
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Editor
export VISUAL="vim"
export EDITOR=$VISUAL

# Color
export CLICOLOR=1

# Paths
typeset -U path
export NODE_PATH=/usr/local/lib/node_modules
export PROJECTS=$HOME/Code

path=($HOME/bin /usr/local/bin $path)

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
