ZSH=$HOME/.zsh

fpath=($ZSH/functions $ZSH/completions $fpath)

autoload -U $ZSH/functions/*(:t)
autoload -U compinit; compinit -i;
autoload colors; colors;

for config ($ZSH/*.zsh) source $config

# ZSH Syntax Highlighting
source $HOME/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
