# oh-my-zsh
ZSH=$HOME/.oh-my-zsh
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
plugins=(git brew rbenv gem bundler rake powder redis-cli vi-mode extract)
source $ZSH/oh-my-zsh.sh

PROJECTS=$HOME/Code

for config_file ($HOME/.zsh/*.zsh) source $config_file

# Z
if [[ -f $HOME/z.sh ]]; then
  . $HOME/z.sh
  function precmd () {
    _z --add "$(pwd -P)"
  }
fi

# Load localrc
[[ -f $HOME/.localrc ]] && . $HOME/.localrc
