ZSH=$HOME/.zsh
autoload -U compinit; compinit -i;
autoload colors; colors;

fpath=($ZSH/functions $ZSH/completions $fpath)
autoload -U $ZSH/functions/*(:t)

for config ($ZSH/*.zsh) source $config

# ZSH Syntax Highlighting
source $HOME/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
